<?php

namespace Database\Seeders;

use App\Models\Booking;
use App\Models\BookingAttempt;
use App\Models\Customer;
use App\Models\Resource;
use App\Models\SchedulingConstraint;
use App\Models\Staff;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        Customer::query()->upsert([
            [
                'id' => 'cust-mira',
                'name' => 'Mira Chen',
                'email' => 'mira.chen@example.com',
                'phone' => '+1 415 555 0198',
                'tier' => 'priority',
                'visit_count' => 18,
                'lifetime_value_cents' => 482500,
                'notes' => 'Prefers morning planning sessions and the north consultation room.',
            ],
            [
                'id' => 'cust-dev',
                'name' => 'Dev Shah',
                'email' => 'dev.shah@example.com',
                'phone' => '+1 415 555 0134',
                'tier' => 'standard',
                'visit_count' => 7,
                'lifetime_value_cents' => 126000,
                'notes' => 'Usually books service setup blocks after lunch.',
            ],
            [
                'id' => 'cust-iris',
                'name' => 'Iris Stone',
                'email' => 'iris.stone@example.com',
                'phone' => '+1 415 555 0177',
                'tier' => 'new',
                'visit_count' => 2,
                'lifetime_value_cents' => 36000,
                'notes' => 'Needs onboarding before any setup session.',
            ],
            [
                'id' => 'cust-maya',
                'name' => 'Maya Ortiz',
                'email' => 'maya.ortiz@example.com',
                'phone' => '+1 415 555 0201',
                'tier' => 'priority',
                'visit_count' => 11,
                'lifetime_value_cents' => 214800,
                'notes' => 'Prefers late morning consults and quick confirmation notes.',
            ],
            [
                'id' => 'cust-omar',
                'name' => 'Omar Reed',
                'email' => 'omar.reed@example.com',
                'phone' => '+1 415 555 0202',
                'tier' => 'standard',
                'visit_count' => 5,
                'lifetime_value_cents' => 94500,
                'notes' => 'Needs station setup with extra buffer for equipment checks.',
            ],
            [
                'id' => 'cust-sana',
                'name' => 'Sana Park',
                'email' => 'sana.park@example.com',
                'phone' => '+1 415 555 0203',
                'tier' => 'standard',
                'visit_count' => 9,
                'lifetime_value_cents' => 176400,
                'notes' => 'Often requests the garden room when available.',
            ],
            [
                'id' => 'cust-nico',
                'name' => 'Nico Vale',
                'email' => 'nico.vale@example.com',
                'phone' => '+1 415 555 0204',
                'tier' => 'new',
                'visit_count' => 1,
                'lifetime_value_cents' => 18000,
                'notes' => 'Needs a callback before a reservation hold is confirmed.',
            ],
            [
                'id' => 'cust-ava',
                'name' => 'Ava Brooks',
                'email' => 'ava.brooks@example.com',
                'phone' => '+1 415 555 0205',
                'tier' => 'priority',
                'visit_count' => 14,
                'lifetime_value_cents' => 309200,
                'notes' => 'Prefers same-day confirmation when a room opens.',
            ],
            [
                'id' => 'cust-owen',
                'name' => 'Owen Hart',
                'email' => 'owen.hart@example.com',
                'phone' => '+1 415 555 0206',
                'tier' => 'standard',
                'visit_count' => 4,
                'lifetime_value_cents' => 72000,
                'notes' => 'Usually books short onboarding before setup work.',
            ],
        ], ['id']);

        Staff::query()->upsert([
            [
                'id' => 'staff-emi',
                'name' => 'Emi Tanaka',
                'role' => 'Reservation lead',
                'skills' => json_encode(['consult', 'onboarding', 'conflict review']),
                'shift_start' => '08:00',
                'shift_end' => '17:00',
                'accepts_overlap' => false,
            ],
            [
                'id' => 'staff-kai',
                'name' => 'Kai Morgan',
                'role' => 'Implementation specialist',
                'skills' => json_encode(['service setup', 'resource setup']),
                'shift_start' => '09:00',
                'shift_end' => '18:00',
                'accepts_overlap' => false,
            ],
            [
                'id' => 'staff-nora',
                'name' => 'Nora Patel',
                'role' => 'Customer operations',
                'skills' => json_encode(['onboarding', 'follow-up']),
                'shift_start' => '08:30',
                'shift_end' => '16:30',
                'accepts_overlap' => false,
            ],
            [
                'id' => 'staff-jo',
                'name' => 'Jo Rivera',
                'role' => 'Room coordinator',
                'skills' => json_encode(['consult', 'room readiness']),
                'shift_start' => '08:00',
                'shift_end' => '16:00',
                'accepts_overlap' => false,
            ],
            [
                'id' => 'staff-lina',
                'name' => 'Lina Brooks',
                'role' => 'Capacity reviewer',
                'skills' => json_encode(['capacity review', 'customer follow-up']),
                'shift_start' => '10:00',
                'shift_end' => '19:00',
                'accepts_overlap' => false,
            ],
        ], ['id']);

        Resource::query()->upsert([
            [
                'id' => 'room-north',
                'name' => 'North consultation room',
                'type' => 'room',
                'capacity' => 1,
                'zone' => 'Front office',
            ],
            [
                'id' => 'room-south',
                'name' => 'South consultation room',
                'type' => 'room',
                'capacity' => 1,
                'zone' => 'Front office',
            ],
            [
                'id' => 'room-garden',
                'name' => 'Garden consultation room',
                'type' => 'room',
                'capacity' => 1,
                'zone' => 'Quiet wing',
            ],
            [
                'id' => 'station-blue',
                'name' => 'Blue service station',
                'type' => 'station',
                'capacity' => 1,
                'zone' => 'Ops floor',
            ],
            [
                'id' => 'station-green',
                'name' => 'Green service station',
                'type' => 'station',
                'capacity' => 1,
                'zone' => 'Ops floor',
            ],
        ], ['id']);

        SchedulingConstraint::query()->upsert([
            [
                'id' => 'svc-consult',
                'service_name' => 'Planning consult',
                'duration_minutes' => 60,
                'buffer_minutes' => 15,
                'required_resource_type' => 'room',
                'booking_window_start' => '08:00',
                'booking_window_end' => '17:00',
                'is_active' => true,
                'mock_payment_policy' => 'authorize-only',
                'notes' => 'Blocks the staff member and one consultation room including a 15 minute buffer.',
            ],
            [
                'id' => 'svc-implementation',
                'service_name' => 'Service setup block',
                'duration_minutes' => 90,
                'buffer_minutes' => 15,
                'required_resource_type' => 'station',
                'booking_window_start' => '09:00',
                'booking_window_end' => '18:00',
                'is_active' => true,
                'mock_payment_policy' => 'authorize-only',
                'notes' => 'Requires a service station. Payment status is recorded for operations review.',
            ],
            [
                'id' => 'svc-onboarding',
                'service_name' => 'Customer onboarding',
                'duration_minutes' => 45,
                'buffer_minutes' => 10,
                'required_resource_type' => 'room',
                'booking_window_start' => '08:00',
                'booking_window_end' => '16:30',
                'is_active' => true,
                'mock_payment_policy' => 'none',
                'notes' => 'Short orientation slot; cancelled holds release immediately.',
            ],
        ], ['id']);

        Booking::query()->upsert([
            [
                'id' => 'bk-1001',
                'customer_id' => 'cust-mira',
                'staff_id' => 'staff-emi',
                'resource_id' => 'room-north',
                'constraint_id' => 'svc-consult',
                'start_at' => '2026-07-14 09:00:00',
                'end_at' => '2026-07-14 10:15:00',
                'status' => 'confirmed',
                'payment_status' => 'mock_authorized',
                'notes' => 'Priority consult; active morning hold for Mira Chen.',
            ],
            [
                'id' => 'bk-1002',
                'customer_id' => 'cust-dev',
                'staff_id' => 'staff-kai',
                'resource_id' => 'station-blue',
                'constraint_id' => 'svc-implementation',
                'start_at' => '2026-07-14 10:30:00',
                'end_at' => '2026-07-14 12:15:00',
                'status' => 'checked_in',
                'payment_status' => 'mock_authorized',
                'notes' => 'In progress service setup block.',
            ],
            [
                'id' => 'bk-1003',
                'customer_id' => 'cust-iris',
                'staff_id' => 'staff-emi',
                'resource_id' => 'room-north',
                'constraint_id' => 'svc-onboarding',
                'start_at' => '2026-07-14 13:00:00',
                'end_at' => '2026-07-14 13:55:00',
                'status' => 'cancelled',
                'payment_status' => 'not_required',
                'notes' => 'Cancelled by customer; capacity is available for another request.',
            ],
            [
                'id' => 'bk-1004',
                'customer_id' => 'cust-owen',
                'staff_id' => 'staff-nora',
                'resource_id' => 'room-south',
                'constraint_id' => 'svc-onboarding',
                'start_at' => '2026-07-15 09:00:00',
                'end_at' => '2026-07-15 09:55:00',
                'status' => 'confirmed',
                'payment_status' => 'not_required',
                'notes' => 'Short onboarding before a later implementation block.',
            ],
            [
                'id' => 'bk-1005',
                'customer_id' => 'cust-maya',
                'staff_id' => 'staff-emi',
                'resource_id' => 'room-north',
                'constraint_id' => 'svc-consult',
                'start_at' => '2026-07-15 11:00:00',
                'end_at' => '2026-07-15 12:15:00',
                'status' => 'confirmed',
                'payment_status' => 'mock_authorized',
                'notes' => 'Planning consult with priority confirmation.',
            ],
            [
                'id' => 'bk-1006',
                'customer_id' => 'cust-omar',
                'staff_id' => 'staff-kai',
                'resource_id' => 'station-blue',
                'constraint_id' => 'svc-implementation',
                'start_at' => '2026-07-16 13:30:00',
                'end_at' => '2026-07-16 15:15:00',
                'status' => 'confirmed',
                'payment_status' => 'mock_authorized',
                'notes' => 'Setup block with station readiness notes.',
            ],
            [
                'id' => 'bk-1007',
                'customer_id' => 'cust-sana',
                'staff_id' => 'staff-jo',
                'resource_id' => 'room-garden',
                'constraint_id' => 'svc-consult',
                'start_at' => '2026-07-17 09:30:00',
                'end_at' => '2026-07-17 10:45:00',
                'status' => 'checked_in',
                'payment_status' => 'mock_authorized',
                'notes' => 'Garden room consult currently checked in.',
            ],
            [
                'id' => 'bk-1008',
                'customer_id' => 'cust-nico',
                'staff_id' => 'staff-nora',
                'resource_id' => 'room-north',
                'constraint_id' => 'svc-onboarding',
                'start_at' => '2026-07-18 10:00:00',
                'end_at' => '2026-07-18 10:55:00',
                'status' => 'cancelled',
                'payment_status' => 'not_required',
                'notes' => 'Customer released the hold after requesting a callback.',
            ],
            [
                'id' => 'bk-1009',
                'customer_id' => 'cust-ava',
                'staff_id' => 'staff-lina',
                'resource_id' => 'room-south',
                'constraint_id' => 'svc-consult',
                'start_at' => '2026-07-20 14:00:00',
                'end_at' => '2026-07-20 15:15:00',
                'status' => 'confirmed',
                'payment_status' => 'mock_authorized',
                'notes' => 'Same-day room confirmation after capacity opened.',
            ],
            [
                'id' => 'bk-1010',
                'customer_id' => 'cust-mira',
                'staff_id' => 'staff-jo',
                'resource_id' => 'room-north',
                'constraint_id' => 'svc-consult',
                'start_at' => '2026-07-21 09:00:00',
                'end_at' => '2026-07-21 10:15:00',
                'status' => 'confirmed',
                'payment_status' => 'mock_authorized',
                'notes' => 'Follow-up planning consult for an existing priority customer.',
            ],
        ], ['id']);

        BookingAttempt::query()->upsert([
            $this->attemptRow(
                'attempt-seed-accepted-mira',
                'cust-mira',
                'staff-emi',
                'room-north',
                'svc-consult',
                'bk-1001',
                '2026-07-14 09:00:00',
                '2026-07-14 10:15:00',
                'accepted',
                null,
                null,
                'Booking accepted. Staff and room capacity were both clear.',
                '2026-06-27 15:35:00',
            ),
            $this->attemptRow(
                'attempt-seed-accepted-dev',
                'cust-dev',
                'staff-kai',
                'station-blue',
                'svc-implementation',
                'bk-1002',
                '2026-07-14 10:30:00',
                '2026-07-14 12:15:00',
                'accepted',
                null,
                null,
                'Booking accepted. Station and staff capacity were clear.',
                '2026-06-27 16:05:00',
            ),
            $this->attemptRow(
                'attempt-seed-blocked-staff',
                'cust-dev',
                'staff-emi',
                'room-south',
                'svc-consult',
                null,
                '2026-07-14 09:30:00',
                '2026-07-14 10:45:00',
                'blocked',
                'staff_overlap',
                'bk-1001',
                'Staff member Emi Tanaka is already assigned to bk-1001.',
                '2026-06-28 08:50:00',
            ),
            $this->attemptRow(
                'attempt-seed-accepted-owen',
                'cust-owen',
                'staff-nora',
                'room-south',
                'svc-onboarding',
                'bk-1004',
                '2026-07-15 09:00:00',
                '2026-07-15 09:55:00',
                'accepted',
                null,
                null,
                'Booking accepted. Onboarding slot was clear.',
                '2026-06-28 12:10:00',
            ),
            $this->attemptRow(
                'attempt-seed-accepted-lena',
                'cust-maya',
                'staff-emi',
                'room-north',
                'svc-consult',
                'bk-1005',
                '2026-07-15 11:00:00',
                '2026-07-15 12:15:00',
                'accepted',
                null,
                null,
                'Booking accepted. Priority consult recorded after capacity review.',
                '2026-06-28 12:25:00',
            ),
            $this->attemptRow(
                'attempt-seed-blocked-resource',
                'cust-sana',
                'staff-lina',
                'room-north',
                'svc-consult',
                null,
                '2026-07-15 11:15:00',
                '2026-07-15 12:30:00',
                'blocked',
                'resource_overlap',
                'bk-1005',
                'Resource North consultation room is already reserved by bk-1005.',
                '2026-06-29 08:20:00',
            ),
            $this->attemptRow(
                'attempt-seed-accepted-omar',
                'cust-omar',
                'staff-kai',
                'station-blue',
                'svc-implementation',
                'bk-1006',
                '2026-07-16 13:30:00',
                '2026-07-16 15:15:00',
                'accepted',
                null,
                null,
                'Booking accepted. Station setup capacity was clear.',
                '2026-06-29 14:30:00',
            ),
            $this->attemptRow(
                'attempt-seed-blocked-station',
                'cust-nico',
                'staff-lina',
                'station-blue',
                'svc-implementation',
                null,
                '2026-07-16 14:00:00',
                '2026-07-16 15:45:00',
                'blocked',
                'resource_overlap',
                'bk-1006',
                'Resource Blue service station is already reserved by bk-1006.',
                '2026-06-30 08:45:00',
            ),
            $this->attemptRow(
                'attempt-seed-accepted-sana',
                'cust-sana',
                'staff-jo',
                'room-garden',
                'svc-consult',
                'bk-1007',
                '2026-07-17 09:30:00',
                '2026-07-17 10:45:00',
                'accepted',
                null,
                null,
                'Booking accepted. Garden room consult was available.',
                '2026-06-30 11:10:00',
            ),
            $this->attemptRow(
                'attempt-seed-blocked-jo',
                'cust-iris',
                'staff-jo',
                'room-south',
                'svc-consult',
                null,
                '2026-07-17 09:45:00',
                '2026-07-17 11:00:00',
                'blocked',
                'staff_overlap',
                'bk-1007',
                'Staff member Jo Rivera is already assigned to bk-1007.',
                '2026-06-30 14:25:00',
            ),
            $this->attemptRow(
                'attempt-seed-outside-window',
                'cust-owen',
                'staff-lina',
                'room-garden',
                'svc-consult',
                null,
                '2026-07-19 18:30:00',
                '2026-07-19 19:45:00',
                'validation_failed',
                'booking_window',
                null,
                'The requested time is outside the configured booking window.',
                '2026-06-30 15:00:00',
            ),
            $this->attemptRow(
                'attempt-seed-payment-hold',
                'cust-nico',
                'staff-lina',
                'room-garden',
                'svc-consult',
                null,
                '2026-07-20 11:00:00',
                '2026-07-20 12:15:00',
                'pending_review',
                'payment_hold',
                null,
                'Reservation hold is waiting for customer confirmation; payment status stays inside the operations workspace.',
                '2026-06-30 16:35:00',
            ),
        ], ['id']);
    }

    /**
     * @return array<string, mixed>
     */
    private function attemptRow(
        string $id,
        string $customerId,
        string $staffId,
        string $resourceId,
        string $constraintId,
        ?string $attemptedBookingId,
        string $startAt,
        string $endAt,
        string $status,
        ?string $conflictKind,
        ?string $blockingBookingId,
        string $reason,
        string $createdAt,
    ): array {
        return [
            'id' => $id,
            'customer_id' => $customerId,
            'staff_id' => $staffId,
            'resource_id' => $resourceId,
            'constraint_id' => $constraintId,
            'attempted_booking_id' => $attemptedBookingId,
            'start_at' => $startAt,
            'end_at' => $endAt,
            'status' => $status,
            'conflict_kind' => $conflictKind,
            'blocking_booking_id' => $blockingBookingId,
            'reason' => $reason,
            'payment_boundary' => 'mock-only',
            'payload' => json_encode([
                'seed_source' => 'booking operations sample',
                'blocking_booking' => $blockingBookingId,
                'accepted_booking' => $attemptedBookingId,
            ], JSON_THROW_ON_ERROR),
            'created_at' => $createdAt,
            'updated_at' => $createdAt,
        ];
    }
}
